import React, { useMemo, useState } from "react";
import { Search, BookOpen, ExternalLink, Loader2, Sparkles, ShieldCheck, Globe2, LockKeyhole, Filter, ArrowRight, FileText, Link2, Copy, CheckCircle2, Circle, Brain, SlidersHorizontal, AlertTriangle } from "lucide-react";
import { fetchMultiAgentSearch } from "../services/api";
import { Thesis } from "../types/thesis";

type Provider = "ThesisVerse" | "OpenAlex" | "Crossref" | "Semantic Scholar" | "PubMed" | "Europe PMC" | "arXiv";
type Source = { id:string; title:string; authors:string[]; year:number|null; venue:string; abstract:string; url:string; doi?:string; citations:number; provider:Provider; openAccess?:boolean; type:string; relevance:number; match:"direct"|"related" };
type Step = { label:string; detail:string };

const STEPS:Step[] = [
 {label:"Understanding your topic",detail:"Normalising the query and identifying the important search terms."},
 {label:"Searching academic sources",detail:"Querying ThesisVerse and the connected scholarly indexes."},
 {label:"Removing duplicates",detail:"Merging repeated records so the same paper is not shown several times."},
 {label:"Checking relevance",detail:"Scoring titles, abstracts and metadata against your exact topic."},
 {label:"Finding research gaps",detail:"Sending the relevant evidence set to the research-analysis layer."},
 {label:"Cross-checking with AI",detail:"Comparing multiple AI perspectives to prioritise useful findings."},
 {label:"Preparing your research map",detail:"Sorting the strongest matches and preparing useful actions."}
];

const STOP=new Set(["the","a","an","of","and","or","in","on","for","to","with","from","by","about","study","research","analysis","using","based"]);
const text=(v:any)=>typeof v==="string"?v.replace(/\s+/g," ").trim():"";
const abstractFromOA=(x:any)=>{if(!x)return "";const a:string[]=[];Object.entries(x).forEach(([w,p]:any)=>(Array.isArray(p)?p:[p]).forEach((i:number)=>a[i]=w));return a.filter(Boolean).join(" ")};
const year=(x:any)=>x?.["date-parts"]?.[0]?.[0]||null;
const tokens=(q:string)=>q.toLowerCase().replace(/[^a-z0-9\s-]/g," ").split(/\s+/).map(x=>x.trim()).filter(x=>x&&!STOP.has(x));
const fieldWords=(s:string)=>s.toLowerCase().replace(/[^a-z0-9\s-]/g," ").split(/\s+/).filter(Boolean);

function relevanceScore(source:Omit<Source,"relevance"|"match">, q:string){
 const ts=tokens(q); if(!ts.length)return 0;
 const title=fieldWords(source.title); const body=fieldWords(`${source.abstract} ${source.venue}`); const phrase=q.toLowerCase().trim(); const titleText=source.title.toLowerCase();
 const titleHits=ts.filter(t=>title.includes(t)).length;
 const bodyHits=ts.filter(t=>body.includes(t)).length;
 const exact=titleText.includes(phrase)?1:0;
 const coverage=titleHits/ts.length;
 const bodyCoverage=bodyHits/ts.length;
 const tokenBonus=ts.reduce((n,t)=>n+(title.some(w=>w===t)?1:0)+(body.some(w=>w===t)?0.25:0),0)/(ts.length*1.25);
 return Math.min(1, exact*0.45+coverage*0.4+bodyCoverage*0.12+tokenBonus*0.03);
}

function classify(source:Omit<Source,"relevance"|"match">,q:string){
 const r=relevanceScore(source,q); const ts=tokens(q); const hay=`${source.title} ${source.abstract} ${source.venue}`.toLowerCase(); const meaningful=ts.filter(t=>hay.includes(t)).length;
 if(ts.length>=2 && meaningful<Math.min(2,ts.length))return {relevance:r,match:"related" as const};
 if(r>=0.58 || (ts.length<=1&&r>=0.45))return {relevance:r,match:"direct" as const};
 if(r>=0.32)return {relevance:r,match:"related" as const};
 return null;
}

async function getJson(url:string,fallback:any){try{const r=await fetch(url);return r.ok?await r.json():fallback}catch{return fallback}}

export const AdvancedResearchExplorerPage:React.FC<{initialQuery?:string;onShowToast?:(t:string,m?:string,type?:"success"|"error"|"info")=>void}>=({initialQuery="",onShowToast})=>{
 const [query,setQuery]=useState(initialQuery); const [sources,setSources]=useState<Source[]>([]); const [loading,setLoading]=useState(false); const [aiLoading,setAiLoading]=useState(false); const [ai,setAi]=useState<any>(null); const [agent,setAgent]=useState<any>(null); const [openOnly,setOpenOnly]=useState(false); const [searched,setSearched]=useState(false); const [step,setStep]=useState(0); const [expanded,setExpanded]=useState<string|null>(null); const [copied,setCopied]=useState<string|null>(null);
 const search=async(raw=query)=>{const q=raw.trim();if(!q)return;setQuery(q);setSearched(true);setLoading(true);setAiLoading(false);setAi(null);setAgent(null);setSources([]);setStep(0);
  try{
   setStep(1);
   const urls={
    tv:`/api/search?q=${encodeURIComponent(q)}&minYear=1900&maxYear=2026&limit=20`,
    oa:`https://api.openalex.org/works?search=${encodeURIComponent(q)}&per_page=20&sort=relevance_score`,
    cr:`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(q)}&rows=20&select=DOI,title,author,published,container-title,URL,type,is-referenced-by-count`,
    ss:`https://api.semanticscholar.org/graph/v1/paper/search?query=${encodeURIComponent(q)}&limit=20&fields=title,authors,year,abstract,venue,url,externalIds,citationCount,openAccessPdf,publicationTypes`,
    pm:`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=${encodeURIComponent(q)}&retmode=json&retmax=12`,
    epmc:`https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=${encodeURIComponent(q)}&format=json&pageSize=15`,
    arxiv:`https://export.arxiv.org/api/query?search_query=all:${encodeURIComponent(q)}&start=0&max_results=12`
   };
   const [tv,oa,cr,ss,pm,epmc,arxiv]=await Promise.all([getJson(urls.tv,{data:[]}),getJson(urls.oa,{results:[]}),getJson(urls.cr,{message:{items:[]}}),getJson(urls.ss,{data:[]}),getJson(urls.pm,{esearchresult:{idlist:[]}}),getJson(urls.epmc,{resultList:{result:[]}}),getJson(urls.arxiv,{feed:{entry:[]}})]);
   const a:Source[]=(tv.data||[]).map((x:any)=>({id:`tv-${x.id}`,title:text(x.title),authors:x.authors||[],year:x.year||null,venue:text(x.university||x.publisher)||"ThesisVerse",abstract:text(x.abstract),url:x.sourceUrl||x.pdfUrl||"#",doi:x.doi,citations:+(x.citationsCount||0),provider:"ThesisVerse",type:x.documentType||"Research",openAccess:!!x.pdfUrl,relevance:0,match:"related"}));
   const b:Source[]=(oa.results||[]).map((x:any)=>({id:`oa-${x.id}`,title:text(x.display_name),authors:(x.authorships||[]).slice(0,6).map((z:any)=>text(z.author?.display_name)).filter(Boolean),year:x.publication_year||null,venue:text(x.primary_location?.source?.display_name)||"OpenAlex",abstract:abstractFromOA(x.abstract_inverted_index),url:x.primary_location?.landing_page_url||x.doi||x.id,doi:x.doi,citations:+(x.cited_by_count||0),provider:"OpenAlex",type:text(x.type)||"Work",openAccess:!!x.open_access?.is_oa,relevance:0,match:"related"}));
   const c:Source[]=(cr.message?.items||[]).map((x:any,i:number)=>({id:`cr-${x.DOI||i}`,title:text(x.title?.[0]||x.title),authors:(x.author||[]).slice(0,6).map((z:any)=>text([z.given,z.family].filter(Boolean).join(" "))).filter(Boolean),year:year(x.published),venue:text(x["container-title"]?.[0]||x["container-title"])||"Crossref",abstract:text(x.abstract?.replace(/<[^>]+>/g," ")),url:x.URL||(x.DOI?`https://doi.org/${x.DOI}`:"#"),doi:x.DOI,citations:+(x["is-referenced-by-count"]||0),provider:"Crossref",type:text(x.type)||"Work",relevance:0,match:"related"}));
   const d:Source[]=(ss.data||[]).map((x:any,i:number)=>({id:`ss-${x.paperId||i}`,title:text(x.title),authors:(x.authors||[]).slice(0,6).map((z:any)=>text(z.name)).filter(Boolean),year:x.year||null,venue:text(x.venue)||"Semantic Scholar",abstract:text(x.abstract),url:x.url||`https://www.semanticscholar.org/paper/${x.paperId}`,doi:x.externalIds?.DOI,citations:+(x.citationCount||0),provider:"Semantic Scholar",type:x.publicationTypes?.[0]||"Research",openAccess:!!x.openAccessPdf?.url,relevance:0,match:"related"}));
   const ids=(pm.esearchresult?.idlist||[]); const e:Source[]=ids.map((id:string)=>({id:`pm-${id}`,title:`PubMed record ${id}`,authors:[],year:null,venue:"PubMed",abstract:"Open the record for bibliographic details and available full-text links.",url:`https://pubmed.ncbi.nlm.nih.gov/${id}/`,citations:0,provider:"PubMed",type:"PubMed record",relevance:0,match:"related"}));
   const f:Source[]=(epmc.resultList?.result||[]).map((x:any,i:number)=>({id:`epmc-${x.id||i}`,title:text(x.title),authors:text(x.authorString).split(",").map(text).filter(Boolean).slice(0,6),year:+(x.pubYear||0)||null,venue:text(x.journalTitle)||"Europe PMC",abstract:text(x.abstractText),url:x.fullTextUrlList?.fullTextUrl?.[0]?.url||`https://europepmc.org/article/${x.source}/${x.id}`,doi:x.doi,citations:+(x.citedByCount||0),provider:"Europe PMC",type:x.pubType||"Article",openAccess:!!x.isOpenAccess,relevance:0,match:"related"}));
   const g:Source[]=(arxiv.feed?.entry||[]).map((x:any,i:number)=>({id:`arxiv-${x.id||i}`,title:text(x.title),authors:(x.author||[]).map((z:any)=>text(z.name)).filter(Boolean).slice(0,6),year:x.published?new Date(x.published).getFullYear():null,venue:"arXiv",abstract:text(x.summary),url:x.id,citations:0,provider:"arXiv",type:"Preprint",openAccess:true,relevance:0,match:"related"}));
   setStep(2);
   const all=[...a,...b,...c,...d,...e,...f,...g];const seen=new Set<string>();const dedup=all.filter(x=>{const k=(x.doi||x.title).toLowerCase().replace(/[^a-z0-9]/g,"");if(!k||seen.has(k))return false;seen.add(k);return true});
   setStep(3);
   const ranked=dedup.map(x=>{const c=classify(x,q);return c?{...x,...c}:null}).filter(Boolean) as Source[];
   ranked.sort((x,y)=>y.relevance-x.relevance || y.citations-x.citations);
   const direct=ranked.filter(x=>x.match==="direct");
   const related=ranked.filter(x=>x.match==="related").slice(0,12);
   const visible=direct.length?ranked.filter(x=>x.match==="direct").slice(0,40):related;
   setSources(visible);
   setStep(4); setLoading(false); setAiLoading(true); setStep(5);
   const thesisLike:Thesis[]=visible.slice(0,15).map(x=>({id:x.id,title:x.title,authors:x.authors,university:x.venue,publisher:x.provider,year:x.year||0,abstract:x.abstract,keywords:tokens(q),subject:"General" as any,degree:"Research",doi:x.doi||"",sourceUrl:x.url,language:"English",citationsCount:x.citations,noveltyScore:Math.round((1-x.relevance)*100),difficultyScore:50,confidenceScore:Math.round(x.relevance*100),researchGap:"",futureDirections:[],methodology:"",keyFindings:[],bibtex:""}));
   const [ar,ag]=await Promise.allSettled([fetch(`/api/ai/analyze-topic`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:q,sources:visible.slice(0,20)})}).then(r=>r.ok?r.json():null),fetchMultiAgentSearch(q,thesisLike)]);if(ar.status==="fulfilled")setAi(ar.value);if(ag.status==="fulfilled")setAgent(ag.value);setAiLoading(false);setStep(6);setStep(7);
  }catch(err:any){setLoading(false);setAiLoading(false);onShowToast?.("Research search failed",err?.message||"Try again","error")}
 };
 const filtered=useMemo(()=>openOnly?sources.filter(x=>x.openAccess):sources,[sources,openOnly]);
 const directCount=sources.filter(x=>x.match==="direct").length; const relatedCount=sources.filter(x=>x.match==="related").length;
 const scholar=`https://scholar.google.com/scholar?q=${encodeURIComponent(query)}`; const unpay=`https://unpaywall.org/products/simple-query-tool?query=${encodeURIComponent(query)}`;
 const copyDoi=async(doi:string)=>{try{await navigator.clipboard?.writeText(doi);setCopied(doi);setTimeout(()=>setCopied(null),1600)}catch{}}
 const metric=(n:number)=>Math.round(Math.max(0,Math.min(100,n)));
 const direct=filtered.filter(x=>x.match==="direct"); const related=filtered.filter(x=>x.match==="related");
 return <div className="min-h-[calc(100vh-120px)] pb-16 space-y-6"><section className="max-w-5xl mx-auto pt-5 sm:pt-9"><div className="text-center"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-500/10 text-indigo-600 dark:text-indigo-300 border border-indigo-500/20 text-[11px] font-black uppercase tracking-wider mb-4"><Sparkles className="w-3.5 h-3.5"/> Advanced Research Explorer</div><h1 className="text-3xl sm:text-5xl font-black tracking-tight text-slate-900 dark:text-white">Search the <span className="text-indigo-600 dark:text-indigo-400">research landscape.</span></h1><p className="mt-3 text-sm sm:text-base text-slate-500 dark:text-slate-400 max-w-3xl mx-auto">Find genuinely relevant papers and theses, understand the evidence, and see where your topic may still have room to be studied.</p></div><form onSubmit={e=>{e.preventDefault();search()}} className="mt-7 p-2 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl flex gap-2"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: Baul song" aria-label="Research topic" className="w-full h-12 pl-12 pr-4 bg-transparent outline-none text-sm sm:text-base text-slate-900 dark:text-white"/><span className="hidden sm:block absolute right-4 top-1/2 -translate-y-1/2 text-[10px] font-bold text-slate-400">Short topics are OK</span></div><button disabled={loading||!query.trim()} className="px-5 sm:px-7 rounded-xl bg-indigo-600 text-white font-bold text-sm disabled:opacity-50 flex items-center gap-2">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<Search className="w-4 h-4"/>}Search</button></form>{searched&&<div className="mt-3 flex flex-wrap justify-center gap-2"><a target="_blank" rel="noreferrer" href={scholar} title="Search the exact topic directly on Google Scholar" className="px-3 py-2 rounded-xl border text-xs font-bold flex gap-1.5 items-center"><Globe2 className="w-3.5 h-3.5"/> Open Google Scholar</a><a target="_blank" rel="noreferrer" href={unpay} title="Look for a legitimate open-access copy" className="px-3 py-2 rounded-xl border text-xs font-bold flex gap-1.5 items-center"><LockKeyhole className="w-3.5 h-3.5"/> Find legal full text</a></div>}</section>
 {searched&&<main className="max-w-6xl mx-auto space-y-5">
  {(loading||aiLoading)&&<section className="rounded-2xl border border-indigo-200 dark:border-indigo-900/60 bg-white dark:bg-slate-900 p-5 sm:p-6 shadow-sm"><div className="flex items-start gap-4"><div className="relative flex flex-col items-center shrink-0"><div className="w-4 h-4 rounded-full bg-indigo-600 ring-4 ring-indigo-500/20 shadow-[0_0_18px_rgba(79,70,229,0.55)]"/><div className="w-1 min-h-[250px] bg-indigo-500/50 rounded-full mt-1"/></div><div className="flex-1 -mt-1"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-wider font-black text-indigo-600">Live search pipeline</p><h2 className="text-lg sm:text-xl font-black text-slate-900 dark:text-white mt-1">{STEPS[Math.min(step,6)].label}</h2><p className="text-xs sm:text-sm text-slate-500 mt-1">{STEPS[Math.min(step,6)].detail}</p></div><Brain className="w-5 h-5 text-indigo-500 shrink-0 animate-pulse"/></div><div className="mt-5 space-y-3">{STEPS.map((s,i)=>{const done=i<step;const active=i===step;return <div key={s.label} className={`flex gap-3 items-start rounded-xl p-2.5 transition-all ${active?"bg-indigo-500/10":""}`}><div className={`w-4 h-4 rounded-full border-2 shrink-0 mt-0.5 flex items-center justify-center ${done?"border-emerald-500 bg-emerald-500 text-white":active?"border-indigo-500 bg-indigo-500/15":"border-slate-300 dark:border-slate-700"}`}>{done&&<CheckCircle2 className="w-3 h-3"/>}{active&&!done&&<span className="w-1.5 h-1.5 rounded-full bg-indigo-500 animate-pulse"/>}</div><div><p className={`text-xs font-bold ${active?"text-indigo-700 dark:text-indigo-300":"text-slate-700 dark:text-slate-300"}`}>{s.label}</p>{active&&<p className="text-[11px] text-slate-500 mt-0.5">{s.detail}</p>}</div></div>})}</div></div></div></section>}
  {!loading&&<div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs text-slate-500">Research map for</p><h2 className="text-2xl font-black text-slate-900 dark:text-white">{query}</h2><p className="text-[11px] text-slate-500 mt-1">Only results that pass the relevance check are shown here.</p></div><div className="flex flex-wrap gap-2 text-[11px] font-bold"><span className="px-3 py-1.5 rounded-full bg-indigo-500/10 text-indigo-600">{directCount} direct matches</span>{relatedCount>0&&<span className="px-3 py-1.5 rounded-full bg-slate-100 dark:bg-slate-800">{relatedCount} related</span>}<button onClick={()=>setOpenOnly(!openOnly)} title="Show only records with a known open-access route" className={`px-3 py-1.5 rounded-full flex items-center gap-1 ${openOnly?'bg-emerald-500/15 text-emerald-600':'bg-slate-100 dark:bg-slate-800'}`}><Filter className="w-3 h-3"/>{openOnly?'Open access only':'All access types'}</button></div></div>}
  {!loading&&<div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4"><div className="flex items-center gap-2 mb-3"><SlidersHorizontal className="w-4 h-4 text-indigo-500"/><h3 className="font-black text-sm text-slate-900 dark:text-white">How these results are selected</h3></div><div className="flex flex-wrap gap-2 text-[10px] font-bold"><span title="Title and abstract strongly match your search terms" className="px-2.5 py-1.5 rounded-full bg-indigo-500/10 text-indigo-600">Direct match</span><span title="Useful broader evidence, shown separately when direct matches are limited" className="px-2.5 py-1.5 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">Related research</span><span title="A known legitimate full-text route is available" className="px-2.5 py-1.5 rounded-full bg-emerald-500/10 text-emerald-600">Open access</span><span title="A DOI is available for persistent identification" className="px-2.5 py-1.5 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">DOI available</span></div></div>}
  {!loading&&ai&&<section className="rounded-2xl border bg-white dark:bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-wider font-black text-indigo-600">AI-assisted overview</p><h3 className="font-black text-lg text-slate-900 dark:text-white mt-1">Research landscape</h3></div><Sparkles className="w-5 h-5 text-indigo-500"/></div><p className="text-sm leading-6 text-slate-600 dark:text-slate-300 mt-2">{text(ai.summary||ai.researchQuestion)||"The relevant source set has been mapped. Use the original records as the evidence layer."}</p>{Array.isArray(ai.researchGaps)&&ai.researchGaps.length>0&&<div className="mt-4 grid sm:grid-cols-2 gap-2">{ai.researchGaps.slice(0,6).map((x:any,i:number)=><div key={i} className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950 text-sm"><b className="text-indigo-500">Research gap {i+1}</b><p className="mt-1 text-slate-600 dark:text-slate-300">{text(x)}</p></div>)}</div>}<div className="mt-5 grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950"><p className="text-[10px] text-slate-500">Evidence coverage</p><p className="text-xl font-black">{metric(sources.length?Math.max(...sources.map(x=>x.relevance))*100:0)}%</p><p className="text-[9px] text-slate-400">strongest topic match</p></div><div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950"><p className="text-[10px] text-slate-500">Research rarity</p><p className="text-xl font-black">{metric(100-(directCount*7))}%</p><p className="text-[9px] text-slate-400">estimated from direct matches</p></div><div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950"><p className="text-[10px] text-slate-500">Opportunity signal</p><p className="text-xl font-black">{metric(100-(directCount*5)+Math.min(15,relatedCount))}%</p><p className="text-[9px] text-slate-400">screening estimate, not a guarantee</p></div><div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950"><p className="text-[10px] text-slate-500">AI agreement</p><p className="text-xl font-black">{Number(agent?.consensusScore||0)}%</p><p className="text-[9px] text-slate-400">cross-check signal</p></div></div></section>}
  {!loading&&agent&&<section className="rounded-2xl bg-slate-950 text-white p-5 border border-indigo-500/20"><div className="flex items-center gap-3"><ShieldCheck className="w-5 h-5 text-emerald-400"/><div><h3 className="font-black">AI cross-check</h3><p className="text-xs text-slate-400">Agreement helps prioritise analysis; it is not proof of a claim.</p></div><span className="ml-auto text-xl font-black text-emerald-400">{Number(agent.consensusScore||0)}%</span></div></section>}
  {!loading&&<section className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden"><div className="p-5 border-b border-slate-200 dark:border-slate-800"><div className="flex items-center justify-between gap-3"><div><h3 className="font-black text-lg text-slate-900 dark:text-white">{direct.length?"Direct matches":"No strong direct matches"}</h3><p className="text-xs text-slate-500 mt-1">{direct.length?"Ranked by how closely each record matches your topic.":"We won't fill the page with unrelated papers. The records below are broader matches."}</p></div><BookOpen className="w-5 h-5 text-indigo-500"/></div></div>{filtered.length===0?<div className="p-10 text-center"><AlertTriangle className="w-8 h-8 mx-auto text-amber-500"/><p className="mt-3 font-bold text-slate-900 dark:text-white">No useful matches found</p><p className="text-sm text-slate-500 mt-1">Try a more specific phrase, or open Google Scholar for a wider search.</p><a href={scholar} target="_blank" rel="noreferrer" className="inline-flex mt-4 px-4 py-2 rounded-xl bg-indigo-600 text-white text-xs font-bold">Open Google Scholar</a></div>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.map(x=><article key={x.id} className="p-4 sm:p-5"><div className="flex gap-4"><div className="p-2.5 rounded-xl bg-indigo-500/10 text-indigo-600 shrink-0 h-fit"><BookOpen className="w-5 h-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 mb-2"><span className={`text-[10px] px-2 py-1 rounded-full font-black ${x.match==="direct"?"bg-indigo-500/10 text-indigo-600":"bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300"}`}>{x.match==="direct"?"Direct match":"Related research"}</span><span className="text-[10px] px-2 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-500 font-bold">{x.provider}</span>{x.openAccess&&<span title="Known open-access route" className="text-[10px] px-2 py-1 rounded-full bg-emerald-500/10 text-emerald-600 font-bold">Open access</span>}<span title="How closely this record matched your query" className="text-[10px] px-2 py-1 rounded-full bg-indigo-500/10 text-indigo-600 font-bold">{Math.round(x.relevance*100)}% relevance</span></div><h4 className="font-black text-base sm:text-lg text-slate-900 dark:text-white leading-snug">{x.title}</h4><p className="text-xs text-slate-500 mt-1">{x.authors.join(", ")||"Author unavailable"}{x.venue?` · ${x.venue}`:""}{x.year?` · ${x.year}`:""}</p>{x.abstract&&<p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 mt-3 leading-5">{expanded===x.id?x.abstract:`${x.abstract.slice(0,300)}${x.abstract.length>300?"…":""}`}</p>}
 <div className="mt-3 grid grid-cols-3 gap-2 max-w-lg"><div title="Query-match signal, not a scientific quality score" className="rounded-xl bg-slate-50 dark:bg-slate-950 p-2"><p className="text-[9px] text-slate-400">Relevance</p><p className="font-black text-sm">{Math.round(x.relevance*100)}%</p></div><div title="Lower saturation can indicate more room for a new angle; this is only a screening estimate" className="rounded-xl bg-slate-50 dark:bg-slate-950 p-2"><p className="text-[9px] text-slate-400">Rarity signal</p><p className="font-black text-sm">{metric(100-Math.round(x.relevance*75))}%</p></div><div title="Citation count is context, not proof of quality" className="rounded-xl bg-slate-50 dark:bg-slate-950 p-2"><p className="text-[9px] text-slate-400">Citation signal</p><p className="font-black text-sm">{metric(Math.log10(x.citations+1)*18)}%</p></div></div>
 <div className="mt-3 flex flex-wrap gap-2">{x.abstract.length>300&&<button onClick={()=>setExpanded(expanded===x.id?null:x.id)} className="px-3 py-2 rounded-xl border text-xs font-bold">{expanded===x.id?"Hide abstract":"Read abstract"}</button>}<a href={x.url} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-xl bg-indigo-600 text-white text-xs font-bold flex items-center gap-1.5" title="Open the original source"><ExternalLink className="w-3.5 h-3.5"/>View paper</a>{x.openAccess&&<a href={x.url} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-xl border border-emerald-500/30 text-emerald-600 text-xs font-bold flex items-center gap-1.5" title="Open the available full-text route"><FileText className="w-3.5 h-3.5"/>PDF / Full text</a>}{x.doi&&<><a href={`https://doi.org/${x.doi}`} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-xl border text-xs font-bold flex items-center gap-1.5"><Link2 className="w-3.5 h-3.5"/>DOI</a><button onClick={()=>copyDoi(x.doi!)} className="px-3 py-2 rounded-xl border text-xs font-bold flex items-center gap-1.5" title="Copy DOI"><Copy className="w-3.5 h-3.5"/>{copied===x.doi?<CheckCircle2 className="w-3.5 h-3.5 text-emerald-500"/>:"Cite"}</button></>}</div>
 <div className="mt-3 flex items-center gap-2 text-[10px] text-slate-400"><ArrowRight className="w-3 h-3 text-indigo-500"/>AI summary and research-gap analysis are available in the landscape above.</div></div></div></article>)}</div>}</section>}
  {!loading&&related.length>0&&direct.length>0&&<section className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/40 p-5"><h3 className="font-black text-lg text-slate-900 dark:text-white">Related research</h3><p className="text-xs text-slate-500 mt-1">Broader matches are kept separate so they don't look like exact answers to your query.</p><div className="mt-3 grid sm:grid-cols-2 gap-3">{related.slice(0,8).map(x=><a key={x.id} href={x.url} target="_blank" rel="noreferrer" className="block p-3 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 hover:border-indigo-400"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-black text-slate-500">{x.provider}</span><span className="text-[10px] font-bold text-slate-400">{Math.round(x.relevance*100)}%</span></div><p className="mt-1 text-sm font-bold text-slate-900 dark:text-white">{x.title}</p></a>)}</div></section>}
  {!loading&&<section className="rounded-2xl border border-indigo-200 dark:border-indigo-900/50 bg-indigo-50 dark:bg-indigo-950/20 p-5"><h3 className="font-black text-indigo-900 dark:text-indigo-200">Need a wider evidence search?</h3><p className="text-sm text-indigo-800/80 dark:text-indigo-300/80 mt-2 leading-6">Google Scholar can expose library links and alternate versions. For inaccessible work, ThesisVerse prioritises legitimate publisher, repository and open-access routes.</p><div className="mt-3 flex flex-wrap gap-2"><a href={scholar} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-xl bg-white dark:bg-slate-900 border text-xs font-bold">Search exact topic on Scholar</a><a href={unpay} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-xl bg-white dark:bg-slate-900 border text-xs font-bold">Find an open copy</a></div></section>}
 </main>}</div>;
};
