import React, { useMemo, useState } from "react";
import { Search, BookOpen, ExternalLink, Loader2, Sparkles, ShieldCheck, Globe2, LockKeyhole, Filter } from "lucide-react";
import { fetchMultiAgentSearch } from "../services/api";
import { Thesis } from "../types/thesis";

type Provider = "ThesisVerse" | "OpenAlex" | "Crossref" | "Semantic Scholar" | "PubMed" | "Europe PMC" | "arXiv" | "CORE";
type Source = { id:string; title:string; authors:string[]; year:number|null; venue:string; abstract:string; url:string; doi?:string; citations:number; provider:Provider; openAccess?:boolean; type:string };

const text=(v:any)=>typeof v==="string"?v.replace(/\s+/g," ").trim():"";
const abstractFromOA=(x:any)=>{if(!x)return "";const a:string[]=[];Object.entries(x).forEach(([w,p]:any)=>(Array.isArray(p)?p:[p]).forEach((i:number)=>a[i]=w));return a.filter(Boolean).join(" ")};
const year=(x:any)=>x?.["date-parts"]?.[0]?.[0]||null;

async function getJson(url:string, fallback:any){try{const r=await fetch(url);return r.ok?await r.json():fallback}catch{return fallback}}

export const AdvancedResearchExplorerPage:React.FC<{initialQuery?:string;onShowToast?:(t:string,m?:string,type?:"success"|"error"|"info")=>void}>=({initialQuery="",onShowToast})=>{
 const [query,setQuery]=useState(initialQuery); const [sources,setSources]=useState<Source[]>([]); const [loading,setLoading]=useState(false); const [aiLoading,setAiLoading]=useState(false); const [ai,setAi]=useState<any>(null); const [agent,setAgent]=useState<any>(null); const [openOnly,setOpenOnly]=useState(false); const [searched,setSearched]=useState(false);
 const search=async(raw=query)=>{const q=raw.trim();if(!q)return;setQuery(q);setSearched(true);setLoading(true);setAi(null);setAgent(null);
  try{
   const urls={
    tv:`/api/search?q=${encodeURIComponent(q)}&minYear=1900&maxYear=2026&limit=20`,
    oa:`https://api.openalex.org/works?search=${encodeURIComponent(q)}&per_page=20&sort=relevance_score`,
    cr:`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(q)}&rows=20&select=DOI,title,author,published,container-title,URL,type,is-referenced-by-count`,
    ss:`https://api.semanticscholar.org/graph/v1/paper/search?query=${encodeURIComponent(q)}&limit=20&fields=title,authors,year,abstract,venue,url,externalIds,citationCount,openAccessPdf,publicationTypes`,
    pm:`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=${encodeURIComponent(q)}&retmode=json&retmax=12`,
    epmc:`https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=${encodeURIComponent(q)}&format=json&pageSize=15`,
    arxiv:`https://export.arxiv.org/api/query?search_query=all:${encodeURIComponent(q)}&start=0&max_results=12`
   };
   const [tv,oa,cr,ss,pm,epmc,arxiv]=await Promise.all([getJson(urls.tv,{data:[]}),getJson(urls.oa,{results:[]}),getJson(urls.cr,{message:{items:[]}}),getJson(urls.ss,{data:[]}),getJson(urls.pm,{esearchresult:{idlist:[]}}),getJson(urls.epmc,{resultList:{result:[]}}),getJson(urls.arxiv,{feed:{entry:[]}})]);
   const a:Source[]=(tv.data||[]).map((x:any)=>({id:`tv-${x.id}`,title:text(x.title),authors:x.authors||[],year:x.year||null,venue:text(x.university||x.publisher)||"ThesisVerse",abstract:text(x.abstract),url:x.sourceUrl||x.pdfUrl||"#",doi:x.doi,citations:+(x.citationsCount||0),provider:"ThesisVerse",type:x.documentType||"Research",openAccess:!!x.pdfUrl}));
   const b:Source[]=(oa.results||[]).map((x:any)=>({id:`oa-${x.id}`,title:text(x.display_name),authors:(x.authorships||[]).slice(0,6).map((z:any)=>text(z.author?.display_name)).filter(Boolean),year:x.publication_year||null,venue:text(x.primary_location?.source?.display_name)||"OpenAlex",abstract:abstractFromOA(x.abstract_inverted_index),url:x.primary_location?.landing_page_url||x.doi||x.id,doi:x.doi,citations:+(x.cited_by_count||0),provider:"OpenAlex",type:text(x.type)||"Work",openAccess:!!x.open_access?.is_oa}));
   const c:Source[]=(cr.message?.items||[]).map((x:any,i:number)=>({id:`cr-${x.DOI||i}`,title:text(x.title?.[0]||x.title),authors:(x.author||[]).slice(0,6).map((z:any)=>text([z.given,z.family].filter(Boolean).join(" "))).filter(Boolean),year:year(x.published),venue:text(x["container-title"]?.[0]||x["container-title"])||"Crossref",abstract:text(x.abstract?.replace(/<[^>]+>/g," ")),url:x.URL||(x.DOI?`https://doi.org/${x.DOI}`:"#"),doi:x.DOI,citations:+(x["is-referenced-by-count"]||0),provider:"Crossref",type:text(x.type)||"Work"}));
   const d:Source[]=(ss.data||[]).map((x:any,i:number)=>({id:`ss-${x.paperId||i}`,title:text(x.title),authors:(x.authors||[]).slice(0,6).map((z:any)=>text(z.name)).filter(Boolean),year:x.year||null,venue:text(x.venue)||"Semantic Scholar",abstract:text(x.abstract),url:x.url||`https://www.semanticscholar.org/paper/${x.paperId}`,doi:x.externalIds?.DOI,citations:+(x.citationCount||0),provider:"Semantic Scholar",type:x.publicationTypes?.[0]||"Research",openAccess:!!x.openAccessPdf?.url}));
   const ids=(pm.esearchresult?.idlist||[]); const e:Source[]=ids.map((id:string)=>({id:`pm-${id}`,title:`PubMed record ${id}`,authors:[],year:null,venue:"PubMed",abstract:"Open the record for bibliographic details and available full-text links.",url:`https://pubmed.ncbi.nlm.nih.gov/${id}/`,citations:0,provider:"PubMed",type:"PubMed record"}));
   const f:Source[]=(epmc.resultList?.result||[]).map((x:any,i:number)=>({id:`epmc-${x.id||i}`,title:text(x.title),authors:text(x.authorString).split(",").map(text).filter(Boolean).slice(0,6),year:+(x.pubYear||0)||null,venue:text(x.journalTitle)||"Europe PMC",abstract:text(x.abstractText),url:x.fullTextUrlList?.fullTextUrl?.[0]?.url||`https://europepmc.org/article/${x.source}/${x.id}`,doi:x.doi,citations:+(x.citedByCount||0),provider:"Europe PMC",type:x.pubType||"Article",openAccess:!!x.isOpenAccess}));
   const g:Source[]=(arxiv.feed?.entry||[]).map((x:any,i:number)=>({id:`arxiv-${x.id||i}`,title:text(x.title),authors:(x.author||[]).map((z:any)=>text(z.name)).filter(Boolean).slice(0,6),year:x.published?new Date(x.published).getFullYear():null,venue:"arXiv",abstract:text(x.summary),url:x.id, citations:0,provider:"arXiv",type:"Preprint",openAccess:true}));
   const all=[...a,...b,...c,...d,...e,...f,...g];const seen=new Set<string>();const unique=all.filter(x=>{const k=(x.doi||x.title).toLowerCase().replace(/[^a-z0-9]/g,"");if(!k||seen.has(k))return false;seen.add(k);return true});setSources(unique);setLoading(false);setAiLoading(true);
   const thesisLike:Thesis[]=unique.slice(0,15).map(x=>({id:x.id,title:x.title,authors:x.authors,university:x.venue,publisher:x.provider,year:x.year||0,abstract:x.abstract,keywords:q.split(/\s+/),subject:"General" as any,degree:"Research",doi:x.doi||"",sourceUrl:x.url,language:"English",citationsCount:x.citations,noveltyScore:50,difficultyScore:50,confidenceScore:80,researchGap:"",futureDirections:[],methodology:"",keyFindings:[],bibtex:""}));
   const [ar,ag]=await Promise.allSettled([fetch(`/api/ai/analyze-topic`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:q,sources:unique.slice(0,20)})}).then(r=>r.ok?r.json():null),fetchMultiAgentSearch(q,thesisLike)]);if(ar.status==="fulfilled")setAi(ar.value);if(ag.status==="fulfilled")setAgent(ag.value);setAiLoading(false);
  }catch(err:any){setLoading(false);setAiLoading(false);onShowToast?.("Research search failed",err?.message||"Try again","error")}
 };
 const filtered=useMemo(()=>openOnly?sources.filter(x=>x.openAccess):sources,[sources,openOnly]);
 const scholar=`https://scholar.google.com/scholar?q=${encodeURIComponent(query)}`; const unpay=`https://unpaywall.org/products/simple-query-tool?query=${encodeURIComponent(query)}`;
 return <div className="min-h-[calc(100vh-120px)] pb-16 space-y-6"><section className="max-w-5xl mx-auto pt-6 sm:pt-10 text-center"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-500/10 text-indigo-600 dark:text-indigo-300 border border-indigo-500/20 text-[11px] font-bold uppercase tracking-wider mb-4"><Sparkles className="w-3.5 h-3.5"/> Advanced Research Explorer</div><h1 className="text-3xl sm:text-5xl font-black tracking-tight text-slate-900 dark:text-white">One search. <span className="text-indigo-600 dark:text-indigo-400">Many scholarly sources.</span></h1><p className="mt-3 text-sm sm:text-base text-slate-500 dark:text-slate-400 max-w-3xl mx-auto">Search ThesisVerse plus major open scholarly indexes, deduplicate results, find legal full text, and let AI map the research landscape.</p><form onSubmit={e=>{e.preventDefault();search()}} className="mt-7 p-2 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl flex gap-2"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: Baul song" className="w-full h-12 pl-12 pr-4 bg-transparent outline-none text-sm sm:text-base text-slate-900 dark:text-white"/></div><button disabled={loading||!query.trim()} className="px-5 sm:px-7 rounded-xl bg-indigo-600 text-white font-bold text-sm disabled:opacity-50 flex items-center gap-2">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<Search className="w-4 h-4"/>}Search</button></form>{searched&&<div className="mt-3 flex flex-wrap justify-center gap-2"><a target="_blank" rel="noreferrer" href={scholar} className="px-3 py-2 rounded-xl border text-xs font-bold flex gap-1.5 items-center"><Globe2 className="w-3.5 h-3.5"/> Google Scholar</a><a target="_blank" rel="noreferrer" href={unpay} className="px-3 py-2 rounded-xl border text-xs font-bold flex gap-1.5 items-center"><LockKeyhole className="w-3.5 h-3.5"/> Legal full text</a></div>}</section>
 {searched&&<main className="max-w-6xl mx-auto space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs text-slate-500">Research map for</p><h2 className="text-2xl font-black text-slate-900 dark:text-white">{query}</h2></div><div className="flex gap-2 text-[11px] font-bold"><span className="px-3 py-1.5 rounded-full bg-slate-100 dark:bg-slate-800">{sources.length} unique records</span><button onClick={()=>setOpenOnly(!openOnly)} className={`px-3 py-1.5 rounded-full flex items-center gap-1 ${openOnly?'bg-emerald-500/15 text-emerald-600':'bg-slate-100 dark:bg-slate-800'}`}><Filter className="w-3 h-3"/>{openOnly?'Open access only':'All access types'}</button></div></div>
 <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-2">{(["ThesisVerse","OpenAlex","Crossref","Semantic Scholar","PubMed","Europe PMC","arXiv"] as Provider[]).map(p=><div key={p} className="rounded-xl border border-slate-200 dark:border-slate-800 p-3 text-center"><p className="text-[10px] font-bold text-slate-500">{p}</p><p className="text-lg font-black text-slate-900 dark:text-white">{sources.filter(x=>x.provider===p).length}</p></div>)}</div>
 {aiLoading&&<div className="rounded-2xl bg-slate-950 text-white p-5 flex items-center gap-3"><Sparkles className="w-5 h-5 text-indigo-300 animate-pulse"/><div><b>AI is mapping the literature…</b><p className="text-xs text-slate-400 mt-1">Comparing relevance, themes, gaps and multiple AI perspectives.</p></div></div>}
 {ai&&<section className="rounded-2xl border bg-white dark:bg-slate-900 p-5"><h3 className="font-black text-lg text-slate-900 dark:text-white">Research landscape</h3><p className="text-sm leading-6 text-slate-600 dark:text-slate-300 mt-2">{text(ai.summary||ai.researchQuestion)||"The source set has been mapped. Use the linked records as the evidence layer."}</p>{Array.isArray(ai.researchGaps)&&ai.researchGaps.length>0&&<div className="mt-4 grid sm:grid-cols-2 gap-2">{ai.researchGaps.slice(0,6).map((x:any,i:number)=><div key={i} className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950 text-sm"><b className="text-indigo-500">Gap {i+1}.</b> {text(x)}</div>)}</div>}</section>}
 {agent&&<section className="rounded-2xl bg-slate-950 text-white p-5 border border-indigo-500/20"><div className="flex items-center gap-3"><ShieldCheck className="w-5 h-5 text-emerald-400"/><div><h3 className="font-black">AI cross-check</h3><p className="text-xs text-slate-400">Agreement helps prioritize analysis; it is not proof.</p></div><span className="ml-auto text-xl font-black text-emerald-400">{Number(agent.consensusScore||0)}%</span></div></section>}
 <section className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden"><div className="p-5 border-b border-slate-200 dark:border-slate-800"><h3 className="font-black text-lg text-slate-900 dark:text-white">Existing research</h3><p className="text-xs text-slate-500 mt-1">Results are deduplicated across providers. Open the original record before relying on a claim.</p></div>{filtered.length===0?<div className="p-10 text-center text-sm text-slate-500">No records match this filter.</div>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.slice(0,40).map(x=><article key={x.id} className="p-4 sm:p-5"><div className="flex gap-4"><div className="p-2.5 rounded-xl bg-indigo-500/10 text-indigo-600 shrink-0"><BookOpen className="w-5 h-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 mb-1"><span className="text-[10px] px-2 py-1 rounded-full bg-indigo-500/10 text-indigo-600 font-bold">{x.provider}</span><span className="text-[10px] text-slate-400">{x.type}</span>{x.openAccess&&<span className="text-[10px] text-emerald-600 font-bold">Open access</span>}</div><h4 className="font-bold text-sm sm:text-base text-slate-900 dark:text-white">{x.title}</h4><p className="text-xs text-slate-500 mt-1">{x.authors.join(", ")||"Author unavailable"}{x.venue?` · ${x.venue}`:""}{x.year?` · ${x.year}`:""}</p>{x.abstract&&<p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 mt-2 line-clamp-3 leading-5">{x.abstract}</p>}<p className="text-[10px] text-slate-400 mt-2">{x.citations} citations{x.doi?" · DOI available":""}</p></div><a href={x.url} target="_blank" rel="noreferrer" className="shrink-0 h-fit px-3 py-2 rounded-xl border text-xs font-bold flex items-center gap-1.5"><ExternalLink className="w-3.5 h-3.5"/>Open</a></div></article>)}</div>}</section>
 <section className="rounded-2xl border border-indigo-200 dark:border-indigo-900/50 bg-indigo-50 dark:bg-indigo-950/20 p-5"><h3 className="font-black text-indigo-900 dark:text-indigo-200">Need a paper you can't access?</h3><p className="text-sm text-indigo-800/80 dark:text-indigo-300/80 mt-2 leading-6">ThesisVerse will prioritize legitimate routes: publisher pages, institutional repositories, author manuscripts and open-access copies. Google Scholar can also show library links and alternate versions. We don't integrate piracy services.</p><div className="mt-3 flex flex-wrap gap-2"><a href={scholar} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-xl bg-white dark:bg-slate-900 border text-xs font-bold">Search Google Scholar</a><a href={unpay} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-xl bg-white dark:bg-slate-900 border text-xs font-bold">Find an open copy</a></div></section>
 </main>}</div>;
};
